hosts:
# Bastions
  - id: 01
    name: Review-Bastion
    remote: 54.245.154.52
    username: ec2-user
    identity: /Users/jason/.ssh/pingidp2.pem
    knownHosts: /Users/jason/.ssh/known_hosts
# Jumped hosts
  - id: 04
    name: Review Ping A
    remote: 172.21.194.80
    username: ec2-user
    identity: /Users/jason/.ssh/pingidp2.pem
    jumpHost: Review-Bastion
  - id: 05
    name: Staging-Federate
    remote: 172.21.194.234
    username: ec2-user
    identity: /Users/jason/.ssh/stagingfed.pem
    jumpHost: Staging-Fedramp-Bastion
  - id: 06
    name: pf-engine2-prod
    remote: 44.231.81.53
    username: ec2-user
    identity: /Users/jason/.ssh/pingprod.pem
tunnels:
# Review
  - id: 02
    name: Review API Gateway
    local: 127.0.0.1:8000
    host: 01
    remote: ccp-internal.gateway.review.innovationlabs.teradata.com:443
    metadata:
      tags:
        - Gateway
        - Review
      color: cyan
      highlight: bright-cyan
  - id: 03
    name: Review Postgres
    local: 0.0.0.0:8432
    host: 01
    remote: postgres.review.innovationlabs.teradata.com:5432
    metadata:
      tags:
        - Postgres
        - Review
      color: cyan
      highlight: bright-cyan
  - id: 04
    name: Review Ping Federate UI
    local: 8999
    host: 01
    remote: 172.21.194.80:9999
    metadata:
      tags:
        - Ping:UI
        - Review
      color: cyan
      highlight: bright-cyan
  - id: 05
    name: Review Ping Federate OAuth
    local: 8031
    host: 01
    remote: 172.21.194.80:9031
    metadata:
      tags:
        - Ping:OAuth
        - Review
      color: cyan
      highlight: bright-cyan
monitor:
  compressed: true
  color:
    enabled: true
    header: bright-yellow
    jump-tunnel: grey
  metrics: [Id, Name, Port, Rcvd, Sent, Open, Jump, Last]
  units: k
  orderBy: rcvd
  orderAscending: true
web:
  port: 8080
