hosts:
# Bastions
  - id: 01
    name: Review-Bastion
    remote: 54.245.154.52
    username: ec2-user
    identity: /Users/jason/.ssh/pingidp2.pem
    knownHosts: /Users/jason/.ssh/known_hosts
  - id: 02
    name: Staging-Bastion
    remote: 35.164.43.75
    username: ec2-user
    identity: /Users/jason/.ssh/pingidp2.pem
    knownHosts: /Users/jason/.ssh/known_hosts
  - id: 03
    name: Staging-Fedramp-Bastion
    remote: 35.93.224.106
    username: ec2-user
    identity: /Users/jason/.ssh/stagingfed.pem
    knownHosts: /Users/jason/.ssh/known_hosts
# Jumped hosts
  - id: 04
    name: Review Ping A
    remote: 172.21.194.80
    username: ec2-user
    identity: /Users/jason/.ssh/pingidp2.pem
    jumpHost: Review-Bastion
  - id: 05
    name: Staging-Federate
    remote: 172.21.194.234
    username: ec2-user
    identity: /Users/jason/.ssh/stagingfed.pem
    jumpHost: Staging-Fedramp-Bastion
  - id: 06
    name: pf-engine2-prod
    remote: 44.231.81.53
    username: ec2-user
    identity: /Users/jason/.ssh/pingprod.pem
tunnels:
# Local
  - id: 01
    name: Local Vault
    local: 8201
    remote: vault.local.innovationlabs.teradata.com:8200
    metadata:
      tags:
        - Vault
        - Local
      color: green
      highlight: bright-green
# Review
  - id: 02
    name: Review API Gateway
    local: 127.0.0.1:8000
    host: 01
    remote: ccp-internal.gateway.review.innovationlabs.teradata.com:443
    metadata:
      tags:
        - Gateway
        - Review
      color: cyan
      highlight: bright-cyan
  - id: 03
    name: Review Postgres
    local: 0.0.0.0:8432
    host: 01
    remote: postgres.review.innovationlabs.teradata.com:5432
    metadata:
      tags:
        - Postgres
        - Review
      color: cyan
      highlight: bright-cyan
  - id: 04
    name: Review Ping Federate UI
    local: 8999
    host: 01
    remote: 172.21.194.80:9999
    metadata:
      tags:
        - Ping:UI
        - Review
      color: cyan
      highlight: bright-cyan
  - id: 05
    name: Review Ping Federate OAuth
    local: 8031
    host: 01
    remote: 172.21.194.80:9031
    metadata:
      tags:
        - Ping:OAuth
        - Review
      color: cyan
      highlight: bright-cyan
  - id: 06
    name: Review Ping Federate Debug
    local: 8030
    host: 01
    remote: 172.21.194.80:8787
    metadata:
      tags:
        - Ping:Debug
        - Review
      color: cyan
      highlight: bright-cyan
  - id: 07
    name: Vault Review
    local: 8208
    host: 01
    remote: vault.internal.teracloud.teradata.com:8200
    metadata:
      tags:
        - Vault
        - Review
      color: cyan
      highlight: bright-cyan
  # Staging
  - id: 08
    name: Staging API Gateway
    local: 7000
    host: 02
    remote: ccp-internal.gateway.staging.innovationlabs.teradata.com:443
    metadata:
      tags:
        - Gateway
        - Staging
      color: white
      highlight: bright-white
  - id: 09
    name: Staging Postgres
    local: 7432
    host: 02
    remote: postgres.staging.innovationlabs.teradata.com:5432
    metadata:
      tags:
        - Postgres
        - Staging
      color: white
      highlight: bright-white
  - id: 10
    name: Staging Ping Federate UI
    local: 7999
    host: 02
    remote: 172.21.194.7:9999
    metadata:
      tags:
        - Ping:UI
        - Staging
      color: white
      highlight: bright-white
  - id: 11
    name: Staging Ping Federate OAuth
    local: 7031
    host: 02
    remote: 172.21.194.7:9031
    metadata:
      tags:
        - Ping:OAuth
        - Staging
      color: white
      highlight: bright-white
  - id: 12
    name: Staging Ping Federate Debug
    local: 7030
    host: 02
    remote: 172.21.194.7:8787
    metadata:
      tags:
        - Ping:Debug
        - Staging
      color: white
      highlight: bright-white
  - id: 13
    name: Vault Staging
    local: 8207
    host: 02
    remote: vault.internal.teracloud.teradata.com:8200
    metadata:
      tags:
        - Vault
        - Staging
      color: white
      highlight: bright-white
  # Staging Fedramp
  - id: 14
    name: Staging Fedramp API Gateway
    local: 5000
    host: 05
    remote: ccp-internal.gateway.staging.fed.innovationlabs.teradata.com:443
    metadata:
      tags:
        - Gateway
        - Staging-Fedramp
      color: yellow
      highlight: bright-yellow
  - id: 15
    name: Staging-Fedramp Postgres
    local: 4432
    host: 05
    remote: postgres.staging.fed.innovationlabs.teradata.com:5432
    metadata:
      tags:
        - Postgres
        - Staging-Fedramp
      color: yellow
      highlight: bright-yellow
#  - id: 16
#    name: Staging-Fedramp Postgres A-record
#    local: 5432
#    host: 05
#    remote: global1-postgres-staging-fedramp.cpau8wk4gum8.us-west-2.rds.amazonaws.com:5432
#    metadata:
#      color: yellow
#      highlight: bright-yellow
  - id: 17
    name: Staging Fedramp Ping Federate UI
    local: 5999
    host: 05
    remote: 172.21.194.234:9999
    metadata:
      tags:
        - Ping:UI
        - Staging-Fedramp
      color: yellow
      highlight: bright-yellow
  - id: 18
    name: Staging Fedramp Ping Federate OAuth
    local: 5031
    host: 05
    remote: 172.21.194.234:9031
    metadata:
      tags:
        - Ping:OAuth
        - Staging-Fedramp
      color: yellow
      highlight: bright-yellow
  - id: 19
    name: Staging Fedramp Ping Federate Debug
    local: 5030
    host: 05
    remote: 127.0.0.1:8787
    metadata:
      tags:
        - Ping:Debug
        - Staging-Fedramp
      color: yellow
      highlight: bright-yellow
  - id: 20
    name: Vault Staging Fedramp
    local: 8204
    host: 03
    remote: vault.internal.teracloud.teradata.com:8200
    metadata:
      tags:
        - Port:8200
        - Vault
        - Staging-Fedramp
      color: yellow
      highlight: bright-yellow
  - id: 21
    name: Vault Staging Fedramp 8200
    local: 8200
    host: 03
    remote: vault.internal.teracloud.teradata.com:8200
    metadata:
      tags:
        - Port:8200
        - Vault
        - Staging-Fedramp
      color: yellow
      highlight: bright-yellow
# LDAP non-prod
  - id: 22
    name: Non-Prod LDAP Could AD
    local: 636
    remote: ldaps.qateradatacloud.com:636
    metadata:
      tags:
        - LDAP
        - Cloud Ad
        - Non-Prod
      color: magenta
      highlight: bright-magenta
  - id: 23
    name: Non-Prod LDAP CS&S
    local: 1636
    remote: ldaps.qacustomer.teradata.com:636
    metadata:
      tags:
        - LDAP
        - CS&S
        - Non-Prod
      color: magenta
      highlight: bright-magenta
  - id: 24
    name: Fedramp LDAP CS&S
    local: 4636
    host: 05
    remote: cds.fedramp.qateradatacloud.com:636
    metadata:
      tags:
        - LDAP
        - CS&S
        - Staging-Fedramp
      color: magenta
      highlight: bright-magenta
# Production
  - id: 25
    name: Production API Gateway
    group: production
    local: 6000
    host: 06
    remote: ccp-internal.gateway.innovationlabs.teradata.com:443
    metadata:
      tags:
        - Gateway
        - Production
      color: red
      highlight: bright-red
monitor:
  compressed: true
  color:
    enabled: true
    header: bright-yellow
    jump-tunnel: grey
  metrics: [Id, Name, Port, Rcvd, Sent, Open, Jump, Last]
  units: k
  orderBy: rcvd
  orderAscending: true
web:
  port: 8080
